### ISSUE TITLE
ALAP bug

### ISSUE THREAD

**Issue by twliCS** [Twl09008181/CAD#1]
931fececca46bcfa0f7361f6060a351222966f09

ALAP的Schedule應該要從output端開始。
![image](https://user-images.githubusercontent.com/81460143/112723189-4603bf00-8f48-11eb-9e28-4e847859f1a1.png)

**Comment by Twl09008181** [comment]
已在56c47f25b2531faee6dc1b8d8a1b636ec3d40a09版修正
